package web.enums;

public enum DepositsEnum {
    LIBERTY_BASIC,
    LIBERTY_BASIC_EXPRESS,
    LIBERTY_STANDARD,
    LIBERTY_STANDARD_EXPRESS,
    LIBERTY_PREMIUM,
    LIBERTY_PLUS_CURRENCY_USD,
    LIBERTY_PLUS_EXPRESS,
    LIBERTY_CHILD,
    LIBERTY_CALCULATED,
    LIBERTY_CURRENCY_EUR


}
