base_url=http://172.17.1.79:30070
user_account_service=http://172.17.1.52:30072/
customer_service=http://172.17.1.52:30070/
info_service=http://172.17.1.79:30084/
credit_service = http://172.17.1.52:30073/
deposit_service = http://172.17.1.52:30074/
deposit_service_new = http://172.17.1.79:30303/
db_url=jdbc:postgresql://172.17.1.79:32432/
db_user=liberty_developer
db_pass=Mgy4Xn1Wkeul
user_service_db=user_service_db
user_account_service_db=user_account_service_db
info_service_db=info_service_db
customer_service_db=customer_service_db
abs-info_service_db=abs-info_service_db
access_token_credit_service = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJ0ZWNoY2F0IiwidXVpZCI6ImE2OWYyNWQ3LTMzMDktNDE2ZC05OWNjLTI0ODk1YmVlMTY3NyJ9.RZPzT8ZDJSO1qbgebO439fsN6y8muhBjpLlviMOUOIc
abs_info_service=http://172.17.1.79:30091/