base_url=http://172.17.1.79:30070
user_account_service=http://172.17.1.52:30072/
customer_service=http://172.17.1.52:30070/
customer_service_2_0=http://172.17.1.52:31070/
customer_service2.0=http://172.17.1.52:31070/
info_service=http://172.17.1.79:30084/
credit_service=http://172.17.1.79:30073/
deposit_service=http://172.17.1.52:30074/
deposit_service_new=http://172.17.1.79:30303/
db_url=jdbc:postgresql://172.17.1.79:32432/
db_user=liberty_developer
db_pass=Mgy4Xn1Wkeul
user_service_db=user_service_db
user_account_service_db=user_account_service_db
info_service_db=info_service_db
deposit_service_db=deposit_service_db
customer_service_db=customer_service_db
abs-info_service_db=abs-info_service_db
access_token_credit_service=eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiI4MDEyOWU5Mi1lMjZlLTRjYTgtYTE1OC0yNzUyYzlkYjE1MDgifQ.bIY64wYuIdXSyqQJjSBytzalgNXI8k1d7oK3LYzKKeE
access_token_insurance_service=eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiI3MzQ4MWVmNS00NzAzLTQ0Y2ItYjhlOS1hMzZjNTgwNTg5NTkiLCJpYXQiOjE3MTM2MjM2ODMsImV4cCI6MTcxMzYyNDI4M30.beA929kXxioxgu20fGACCyKTiTxm8DXDhMHXAi6RYoU
access_token_investment_service=eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiI4MDEyOWU5Mi1lMjZlLTRjYTgtYTE1OC0yNzUyYzlkYjE1MDgiLCJpYXQiOjE3MTUxNzE3MDAsImV4cCI6MTkxNTE3MjMwMH0.lgGyMgSglFmmoyTNxkY55lHOKaV2PuKXaB7OfKzBKS0
credit_service_db=credit_service_db
abs_info_service=http://172.17.1.79:30091/
abs_client_service=http://172.17.1.79:30088/
account_service=http://172.17.1.79:30303/
card_service=http://172.17.1.79:30303/
insurance_service=http://172.17.1.79:30081/
insurance_service_policy=http://172.17.1.79:30303/
insurance_service_polices=http://172.17.1.79:30303/
popular_insurance_products=172.17.1.79:30303/
insurance_service_db=insurance_service_db
investment_service=http://172.17.1.79:30303/

