base_url=http://172.17.1.79:30070
user_account_service=http://172.17.1.52:30072
db_url=jdbc:postgresql://
db_host=172.17.1.79
db_port=32432
db_user=liberty_developer
db_pass=Mgy4Xn1Wkeul
user_service_db=user_service_db
user_account_service_db=user_account_service_db
info_service_db=info_service_db